# MkDocs configuration for builds with material theme
INHERIT: mkdocs-base.yml

site_url: 'https://docs.percona.com/percona-distribution-for-mysql/'

plugins:
  section-index: {}
  
#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: UA-343802-3